<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>MCGame</RootNamespace>
    <nullable>enable</nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <Target
    Name="Husky"
    AfterTargets="Restore"
    Condition="'$(HUSKY)' != 0"
    Inputs="./.config/dotnet-tools.json"
    Outputs="./.husky/_/install.stamp"
  >
    <Exec
      Command="dotnet tool restore"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
    />
    <Exec
      Command="dotnet husky install"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
      WorkingDirectory="."
    />
    <Touch Files="./.husky/_/install.stamp" AlwaysCreate="true" Condition="Exists('./.husky/_')" />
    <ItemGroup>
      <FileWrites Include="./.husky/_/install.stamp" />
    </ItemGroup>
  </Target>
</Project>
